server:
  port: 8008

spring:
  application:
    name: auth-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/movielens
    username: movielens
    password: movielens

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

security:
  jwt:
    secret: "99fb30f67cc30aecac63e9b0145802bc"
    expiration-seconds: 3600
