{{- if .Values.services.apiGateway.enabled }}
{{- $svc := .Values.services.apiGateway }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: {{ $svc.serviceType | default "ClusterIP" }}
  selector:
    app: {{ $svc.name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
{{- end }}
