{{- if .Values.elasticsearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movielens-elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movielens-elasticsearch
  template:
    metadata:
      labels:
        app: movielens-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          ports:
            - containerPort: {{ .Values.elasticsearch.portHttp }}
            - containerPort: {{ .Values.elasticsearch.portTransport }}
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
{{- end }}
