{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movielens-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movielens-postgres
  template:
    metadata:
      labels:
        app: movielens-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db.name | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.db.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.db.password | quote }}
          # you can mount PV later; for now ephemeral
{{- end }}
