global:
  imageTag: "master-a447bb9"

services:
  discovery:
    tag: "master-a447bb9"
  catalog:
    tag: "master-a447bb9"
  ratings:
    tag: "master-a447bb9"
  recommendation:
    tag: "master-a447bb9"
  auth:
    tag: "master-a447bb9"
  apiGateway:
    tag: "master-a447bb9"