server:
  port: 8082

spring:
  application:
    name: recommendation-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/movielens
    username: movielens
    password: movielens

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/movielens
    username: movielens
    password: movielens


eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

ratings:
  grpc:
    host: ratings-service
    port: 9090

catalog:
  grpc:
    host: catalog-service
    port: 9091

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
