server:
  port: 8082

spring:
  application:
    name: recommendation-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/movielens
    username: movielens
    password: movielens

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/movielens
    username: movielens
    password: movielens


eureka:
  client:
    enabled: false

ratings:
  grpc:
    host: localhost
    port: 9090

catalog:
  grpc:
    host: localhost
    port: 9091

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
