spring:
  main:
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:5433/movielens
    username: movielens
    password: movielens

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
